### ISSUE TITLE
Convert a date to a timestamp

### ISSUE THREAD

**Issue by fpeterschmitt** [wiibaa/logstash-filter-date_formatter#1]
Hi,

I don't see any ability to convert a "textual" date to a simple timestamp.

Would you consider implementing that?

Thanks

**Comment by wiibaa** [comment]
Because this use case is the purpose of the main date filter => https://github.com/logstash-plugins/logstash-filter-date

**Comment by fpeterschmitt** [comment]
No, using the date filter returns a string in ISO format. It can parse the date in any format, but doesn't store it in any wanted format.

**Comment by fpeterschmitt** [comment]
Well, I think there is something strange…

```
        date {
            match => ["date_log", "ISO8601"]
            timezone => "Europe/Paris"
        }
        date {
            match => ["date_log", "ISO8601"]
            timezone => "Europe/Paris"
            target => "timestamp"
        }
```

The first `date` filter converts succesfuly to an integer timestamp in the `@timestamp` field, but the `timestamp` field is a string formatted date…

Might be an issue with the date filter after all, or some type autodetection.

**Comment by wiibaa** [comment]
the date filter create an internal logstash:timestamp object in UTC from an input string.
When finally outputted **as a string** is it always ISO8601, that's why date_formatter can help in a config like

```
date {
        match => ["date_log", "ISO8601"]
        timezone => "Europe/Paris"
        target => "timestamp"
    }
date_formatter {
       source => "timestamp"
       target => "locale_timestamp"
       pattern => "EEE, dd MMM yyyy"
       locale => "fr-FR"
        timezone => "Europe/Paris"
    }
```

**Comment by fpeterschmitt** [comment]
That's strange because when I use date with the default target, `@timestamp`, i get an integer timestamp corresponding to the input date string used.

So I don't have any way to get an integer timestamp from a date string, besides `@timestamp`. But I need `timestamp`, not `@timestamp`.
